@Library('apwide-jenkins-shared-lib@feature/timeout') _

pipeline {
    agent any
    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '1'))
    }
//    triggers {
//        cron('* * * * *') // every 1 minute
//    }
    environment {
//        APW_JIRA_BASE_URL = 'http://mycompany.com/jira' // these variables can be defined at different level: jenkins global properties, pipeline level, stage level
//        APW_JIRA_CREDENTIALS_ID = 'jira-credentials'
        APW_GOLIVE_CLOUD_CREDENTIALS_ID = 'goliveCloudCredentialsId' // generate a token from golive, add it as simple secret in jenkins credentials, and provides the id here
        APW_APPLICATION_SCHEME_ID = 1
        APW_UNAVAILABLE_STATUS = 'Down'
        APW_AVAILABLE_STATUS = 'Up'
        APW_APPLICATION = 'Jira'
        APW_BUILD_FAIL_ON_ERROR = false
//        APW_LOG_LEVEL = 'OFF'
    }
    stages {
        stage('Create Jira Application') {
            steps {
                apwCreateApplication(httpRequestOptions: [
                        timeout: 10,
                        validResponseCodes: "400"
                ])
                apwGetEnvironments(httpRequestOptions: [
                        timeout: 1
                ])
            }

        }
    }
}