@Library('jira-jenkins-shared-lib') _

pipeline {
    agent any
    environment {
        JIRA_BASE_URL = 'http://jira-ecommerce'
        JIRA_CREDENTIALS_ID = 'jira-ecommerce-admin'
        APW_APPLICATION = 'eCommerce'
        APW_UNAVAILABLE_STATUS = 'Down'
        APW_AVAILABLE_STATUS = 'Up'
    }
    stages {
        stage('Check Dev Environment') {
            steps {
                // no checkStatus closure provided, so, will use environment URL in Apwide Golive to check the status
                apwCheckEnvironmentStatus category:'DEV'
            }
        }
        stage('Check Demo Environment') {
            steps {
                apwCheckEnvironmentStatus category:'Demo'
            }
        }
        stage('Check Production Environment') {
            steps {
                apwCheckEnvironmentStatus category:'Production'
            }
        }
    }
}
