@Library('apwide-jenkins-shared-lib') _

pipeline {
    agent any
    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '1'))
    }
    triggers {
        cron('* * * * *') // every 1 minute
    }
    environment {
//        APW_JIRA_BASE_URL = 'http://mycompany.com/jira' // these variables can be defined at different level: jenkins global properties, pipeline level, stage level
//        APW_JIRA_CREDENTIALS_ID = 'jira-credentials'
        APW_UNAVAILABLE_STATUS = 'Down'
        APW_AVAILABLE_STATUS = 'Up'
        APW_APPLICATION = 'eCommerce'
    }
    stages {
        stage('Monitor eCommerce environments') {
            steps {
                apwCheckEnvironmentsStatus() //use variables to select all of the eCommerce application environments to monitor
            }

        }
    }
}